### ISSUE TITLE
Nvim error at startup

### ISSUE THREAD

**Issue by layaachmad** [xshin404/myTermux#12]
When i type nvim
It shows this

Error detected while processing /data/data/com.termux/files/home/.config/nvim/init.lua:
E5112: Error while creating lua chunk: /data/data/com.termux/files/home/.config/nvim/init.lua:3:
 unexpected symbol near ','
Error detected while processing BufReadPost Autocommands for "*":
&termguicolors must be set
Press ENTER or type command to continue

**Comment by xshin404** [comment]
> When i type nvim
> It shows this
> 
> Error detected while processing /data/data/com.termux/files/home/.config/nvim/init.lua:
> E5112: Error while creating lua chunk: /data/data/com.termux/files/home/.config/nvim/init.lua:3:
> unexpected symbol near ','
> Error detected while processing BufReadPost Autocommands for "*":
> &termguicolors must be set
> Press ENTER or type command to continue

What's your Termux version, Playstore or F-Droid?  and can you check your neovim version with the nvim -v command.  Because for neovim support configuration file with Lua language is in version v.0.5.0
