### ISSUE TITLE
Stuck after logging in.

### ISSUE THREAD

**Issue by xEpic0821** [xshin404/myTermux#14]
I am using Termux v0.117. After installing and restarting termux and logging with default username and password i am stuck with this screen. After doing Ctrl+C only it gives me prompt to type anything and why are these extra keys in middle of the screen?
![Screenshot_20210901-115542_Termux](https://user-images.githubusercontent.com/67584120/131621561-4af99256-1345-4e84-82de-19525b1188ff.png)

Edit: Removing fullscreen = true line from termux-properties seems to solve extra keys in the middle of screen issue but black screen after logging in is still present. I faced two more issues.
1. Can't add extra keys. When i try to do so it's giving me this error:
     Could not load and set the "extra-keys" property from the properties file: 
     org.json.JSONException: Unterminated array at character 89 of [['ESC', ','','BACK 
     SLASH','=','^','$','()','{}','[]',{key: KEYBOARD, popup: DRAWER}],>
2. In login screen if we typed wrong password and try to clear with backspace, instead of clearing 
     it will just keep on adding.

**Comment by xshin404** [comment]
> I am using Termux v0.117. After installing and restarting termux and logging with default username and password i am stuck with this screen. After doing Ctrl+C only it gives me prompt to type anything and why are these extra keys in middle of the screen?

1. I think the cause of the stuck is because of rxfetch, you can press `CTRL` + `C` and edit this text in the ~/.autostart file

![image](https://user-images.githubusercontent.com/66439853/131652805-62d46ed0-4066-4362-a32d-a8023ea23aed.png)

Change `rx` to `rxfetch` and make sure you already installed application Plugin `Termux:API` on `Playstore` / `F-Droid` (Adjust to the installed Termux version )  or you can give comment to this text

2. for the problem the extra button is in the middle I think it's because of the effect of `termux.properties` where the value is `use-fullscreen-workaround = true` you can comment on that text to disable it

![image](https://user-images.githubusercontent.com/66439853/131655014-aa48dbf8-900b-4a6e-8e9b-6378e982269a.png)

3. For the login script problem when deleting characters and not being deleted, there is indeed a bug, the way to solve it is by editing the `~/.scripts/login.sh` file

Give comment on the text `Show Password *` down and uncomment `Hidden Password` down 
![image](https://user-images.githubusercontent.com/66439853/131654843-6ef98454-2db7-4e04-8c65-19d21b65cd91.png)

**Comment by xEpic0821** [comment]
> > I am using Termux v0.117. After installing and restarting termux and logging with default username and password i am stuck with this screen. After doing Ctrl+C only it gives me prompt to type anything and why are these extra keys in middle of the screen?
> 
> 1. I think the cause of the stuck is because of rxfetch, you can press `CTRL` + `C` and edit this text in the ~/.autostart file
> 
> ![image](https://user-images.githubusercontent.com/66439853/131652805-62d46ed0-4066-4362-a32d-a8023ea23aed.png)
> 
> Change `rx` to `rxfetch` and make sure you already installed application Plugin `Termux:API` on `Playstore` / `F-Droid` (Adjust to the installed Termux version ) or you can give comment to this text
> 
> 1. for the problem the extra button is in the middle I think it's because of the effect of `termux.properties` where the value is `use-fullscreen-workaround = true` you can comment on that text to disable it
> 
> ![image](https://user-images.githubusercontent.com/66439853/131655014-aa48dbf8-900b-4a6e-8e9b-6378e982269a.png)
> 
> 1. For the login script problem when deleting characters and not being deleted, there is indeed a bug, the way to solve it is by editing the `~/.scripts/login.sh` file
> 
> Give comment on the text `Show Password *` down and uncomment `Hidden Password` down
> ![image](https://user-images.githubusercontent.com/66439853/131654843-6ef98454-2db7-4e04-8c65-19d21b65cd91.png)

Thanks for responding.

> > I am using Termux v0.117. After installing and restarting termux and logging with default username and password i am stuck with this screen. After doing Ctrl+C only it gives me prompt to type anything and why are these extra keys in middle of the screen?
> 
> 1. I think the cause of the stuck is because of rxfetch, you can press `CTRL` + `C` and edit this text in the ~/.autostart file
> 
> ![image](https://user-images.githubusercontent.com/66439853/131652805-62d46ed0-4066-4362-a32d-a8023ea23aed.png)
> 
> Change `rx` to `rxfetch` and make sure you already installed application Plugin `Termux:API` on `Playstore` / `F-Droid` (Adjust to the installed Termux version ) or you can give comment to this text
> 
> 1. for the problem the extra button is in the middle I think it's because of the effect of `termux.properties` where the value is `use-fullscreen-workaround = true` you can comment on that text to disable it
> 
> ![image](https://user-images.githubusercontent.com/66439853/131655014-aa48dbf8-900b-4a6e-8e9b-6378e982269a.png)
> 
> 1. For the login script problem when deleting characters and not being deleted, there is indeed a bug, the way to solve it is by editing the `~/.scripts/login.sh` file
> 
> Give comment on the text `Show Password *` down and uncomment `Hidden Password` down
> ![image](https://user-images.githubusercontent.com/66439853/131654843-6ef98454-2db7-4e04-8c65-19d21b65cd91.png)

Thanks for responding. Your guide fixed most of the issue but still I can't add extra keys. Whenever i try to add and restart termux, i am getting this error.

### Could not load and set the "extra-keys" property from the properties file:
org.json.JSONException: Unterminated array at character 89 of [['ESC', ','','BACK
SLASH','=','^','$','()','{}','[]',{key: KEYBOARD, popup: DRAWER}],>

**Comment by xEpic0821** [comment]
> > I am using Termux v0.117. After installing and restarting termux and logging with default username and password i am stuck with this screen. After doing Ctrl+C only it gives me prompt to type anything and why are these extra keys in middle of the screen?
> 
> 1. I think the cause of the stuck is because of rxfetch, you can press `CTRL` + `C` and edit this text in the ~/.autostart file
> 
> ![image](https://user-images.githubusercontent.com/66439853/131652805-62d46ed0-4066-4362-a32d-a8023ea23aed.png)
> 
> Change `rx` to `rxfetch` and make sure you already installed application Plugin `Termux:API` on `Playstore` / `F-Droid` (Adjust to the installed Termux version ) or you can give comment to this text
> 
> 1. for the problem the extra button is in the middle I think it's because of the effect of `termux.properties` where the value is `use-fullscreen-workaround = true` you can comment on that text to disable it
> 
> ![image](https://user-images.githubusercontent.com/66439853/131655014-aa48dbf8-900b-4a6e-8e9b-6378e982269a.png)
> 
> 1. For the login script problem when deleting characters and not being deleted, there is indeed a bug, the way to solve it is by editing the `~/.scripts/login.sh` file
> 
> Give comment on the text `Show Password *` down and uncomment `Hidden Password` down
> ![image](https://user-images.githubusercontent.com/66439853/131654843-6ef98454-2db7-4e04-8c65-19d21b65cd91.png)

Thanks for responding. Your guide fixed most of the issue but still I can't add extra keys. Whenever i try to add and restart termux, i am getting this error.

`
Could not load and set the "extra-keys" property from the properties file:
org.json.JSONException: Unterminated array at character 89 of [['ESC', ','','BACK
SLASH','=','^','$','()','{}','[]',{key: KEYBOARD, popup: DRAWER}],>
`

**Comment by xshin404** [comment]
![image](https://user-images.githubusercontent.com/66439853/131669473-d148d51b-f973-4e62-b003-01db2bd5f092.png)

ERROR occurs because there is an error in the configuration, I have tried to imitate the extra-keys you want and no error occurs

Maybe because of comma placement etc

`extra-keys = [['ESC', ',', 'BACKSLASH', '=', '^', '$', '()', '{}', '[]', {key: KEYBOARD, popup: DRAWER}]]`
