### ISSUE TITLE
Vim mode changed to icon

### ISSUE THREAD

**Issue by GitHubNeko** [xshin404/myTermux#16]
Vim input mode changed to icon
Could you give me the configuration options to change？:-)
- ![IMG_20211002_090751](https://user-images.githubusercontent.com/83487691/135699708-ee39a43b-874f-418f-9652-35b8c27cb92a.jpg)

**Comment by xshin404** [comment]
> Vim input mode changed to icon Could you give me the configuration options to change？:-)
> 
* ![IMG_20211002_090751](https://user-images.githubusercontent.com/83487691/135699708-ee39a43b-874f-418f-9652-35b8c27cb92a.jpg)

See [NvChad Docs](https://nvchad.netlify.app/config) or [Repository](https://github.com/NvChad/NvChad)
