### ISSUE TITLE
xzy

### ISSUE THREAD

**Issue by Yayan-XD** [xshin404/myTermux#22]
Why after i install but not the same as the pict result on your github?

**Comment by xshin404** [comment]
> Why after i install but not the same as the pict result on your github?

Which one?

**Comment by Yayan-XD** [comment]
> > Why after i install but not the same as the pict result on your github?
> 
> Which one?

Script myTermux

**Comment by Yayan-XD** [comment]
do you have wa or fb?

**Comment by xshin404** [comment]
> I want to ask because I run the run error

Which error?

**Comment by Yayan-XD** [comment]
its install time
