### ISSUE TITLE
After the command ./install.sh help, what do I do

### ISSUE THREAD

**Issue by gowwe** [xshin404/myTermux#5]
After the command ./install.sh help, what do I do

**Comment by xshin404** [comment]
You must choose the installation type, between lightweight and full installation

**Comment by gowwe** [comment]
I want a full installation

في الأحد، ٢٨ مارس ٢٠٢١ ٢:٤١ ص xShin ***@***.***> كتب:

**Comment by xshin404** [comment]
Run "./install.sh full" to full installation

On help option "./install.sh help" i have written it. Why you asking for the installation?

**Comment by gowwe** [comment]
Thanks

في الاثنين، ٢٩ مارس ٢٠٢١ ٧:٤٩ م xShin ***@***.***> كتب:
